#$ definicja jednostek
from ..units import cunit # przypisanie klasy do zmiennej, mniej pisania
cu   = cunit(1, {}    )
kN   = cunit(1, 'kN'  )
m    = cunit(1, 'm'   )
rad  = cunit(1, 'rad' )
mrad = cunit(1, 'mrad')
C    = cunit(1, '°C'  )
s    = cunit(1, 's'   )
deg  = cunit(1, 'deg' )
kNm  = cunit(1, 'kN m')
kg   = cunit(1, 'kg'  )
ton  = cunit(1, 't'   )
K    = cunit(1, 'K'   )
km   = cunit(1, 'km'  )
dm   = cunit(1, 'dm'  )
cm   = cunit(1, 'cm'  )
mm   = cunit(1, 'mm'  )
GN   = cunit(1, 'GN'  )
MN   = cunit(1, 'MN'  )
MNm  = cunit(1, 'MN m')
N    = cunit(1, 'N'   )
yr   = cunit(1, 'yr'  )
day  = cunit(1, 'day' )
hr   = cunit(1, 'hr'  )
mn   = cunit(1, 'min' )
GPa  = cunit(1, 'GPa' )
MPa  = cunit(1, 'MPa' )
kPa  = cunit(1, 'kPa' )
Pa   = cunit(1, 'Pa'  )
Hz   = cunit(1, 'Hz'  )
del cunit
